nadavWeisler/PsychInfo

- src/app/[lng]/Components/AdminComp/IncomingMistakes.tsx
- src/app/[lng]/Components/AdminComp/IncomingRequests.tsx
- src/app/[lng]/Components/AdminComp/RequestAccordion.tsx
- src/app/[lng]/Components/FoundMistake/FoundMistakeAccordion.tsx
- src/app/[lng]/Components/FoundMistake/FoundMistakeAccordionContent.tsx
- src/app/[lng]/Components/ResultComp/Accordion.module.css
- src/app/[lng]/Components/ResultComp/AccordionContent.tsx
- src/app/[lng]/Components/ResultComp/CustomAccordion.tsx
- src/app/[lng]/general/interfaces.tsx
accordion to the new style
Fixes #87
> change request accordion and mistake

- src/app/[lng]/Components/AdminComp/RequestAccordion.tsx
- src/app/[lng]/Components/ResultComp/AccordionContent.tsx
- src/app/[lng]/upload/page.tsx
- src/i18n/locales/en/translation.json
- src/i18n/locales/he/translation.json
> Upload sucess as popup / alert

- src/app/[lng]/Components/ResultComp/AccordionContent.tsx
> תוצאות - שהתוכן יהיה כתוב בפסקאות נפרדות - בדיוק כמו שמעלים את זה

- src/app/[lng]/Components/ResultComp/AccordionContent.tsx
- src/app/[lng]/upload/page.tsx
- src/app/[lng]/upload/select.module.css
> Change background to light colors

- src/app/[lng]/Components/AdminComp/PopUpList.tsx
- src/app/[lng]/Components/AdminComp/RequestAccordion.tsx
- src/app/[lng]/Components/ResultComp/AccordionContent.tsx
- src/app/[lng]/general/utils.tsx
> fix admin page issue

- src/app/[lng]/Components/ResultComp/Accordion.module.css
- src/app/[lng]/general/filters.json
> באג בתצוגה בטלפון של הנושאים לדוגמה בעמוד הבית

- src/app/[lng]/Components/AdminComp/EditContentDialog.tsx
- src/app/[lng]/Components/ResultComp/ShareDialog.tsx
> update content dialog and share dialog overlap accordion

- src/app/[lng]/Components/UI/NavBar.tsx
- src/i18n/locales/en/translation.json
- src/i18n/locales/he/translation.json
> Replace home link in navbar to "PsychInfo"  and the logo

- src/app/[lng]/Components/AdminComp/PopUpList.tsx
- src/app/[lng]/Components/addString.tsx
- src/app/[lng]/upload/page.tsx
> הוספת תגיות וארגונים - רק בעמוד האדמין

- package-lock.json
- package.json
> Upgrade to next,js 14 version

- src/app/[lng]/Components/Wizard/Wizard.tsx
> fix critical routing issue to results

- src/app/layout.tsx
> Fix the hydration error

- src/app/layout.tsx
> fix import issue

- src/app/[lng]/Components/UI/NavBar.style.ts
to left when screen is not wide
Fixes #164
> Localization drop down is not fit

- src/app/[lng]/Components/Wizard/Wizard.tsx
- src/app/[lng]/Components/gallary/gallary.tsx
- src/app/[lng]/firebase/commands.ts
- src/app/[lng]/upload/page.tsx
- src/i18n/locales/arb/translation.json
- src/i18n/locales/en/translation.json
- src/i18n/locales/he/translation.json
- src/i18n/locales/rus/translation.json
> הורדת הסינונים לפי הארגונים בתהליך ה"פרסונליזציה" + בהעלאת התוכן

- src/app/[lng]/upload/page.tsx
> Header in Upload is in wrong font

- src/app/[lng]/Components/UI/WelcomeMsg.style.ts
- src/app/[lng]/Components/UI/WelcomeMsg.tsx
- src/app/[lng]/home-page/page.tsx
> Add border / seperator between selected section and welcom msg

- src/app/[lng]/about-us/page.tsx
> Different photos for Anna and Tania

- src/app/[lng]/about-us/page.style.ts
- src/app/[lng]/about-us/page.tsx
> Justify credits page

- src/app/[lng]/Components/UI/NavBar.style.ts
- src/app/[lng]/Components/UI/NavBar.tsx
> Admin, not in center, maybe replace with Icon

- src/app/[lng]/about-us/page.tsx
> Add linkedIn \ website \ mail icon in credits section
